inherit_from: configs/Replica/replica.yaml
mapping:
  # bound: [[-2,3.2],[-1.7,2.7],[-1.2,2.0]]
  # marching_cubes_bound: [[-1.9,3.1],[-1.6,2.6],[-1.1,1.8]]
  bound:  [[-3,3],[-3,3],[-0.5,1.5]] #VICON ROOM
  marching_cubes_bound:  [[-3,3],[-3,3],[-0.5,1.5]]
  keyframe_every: 1
  map_every: 1
  

mesh: 
  render_color: True
  vis: 25  


cam: #oogway
  H: 360
  W: 640
  fx: 498.37325
  fy: 498.37325
  cx: 327.03568499999994
  cy: 181.04722166666664
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
  near: 0
  far: 5
  depth_trunc: 100. # this is for calculating sdf loss
  max_depth: 10000. # where I cut my depth pixel value


data:
  downsample: 1
  sc_factor: 1
  output: output/turtlebot
  exp_name: test
  load_path: output/Apartment/apartment_centralized/agent_0/checkpoint12594.pt

multi_agents:
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: False
  #alpha: 0.15 # DSGD
  alpha: 0.02 # DSGT

