inherit_from: configs/scannet/scannet.yaml
mapping:
  bound: [[0.5,9.1],[-0.3,7.8],[-0.3,2.7]]
  marching_cubes_bound: [[0.5,9.1],[-0.3,7.8],[-0.3,2.7]]
  keyframe_every: 5
  map_every: 5

mesh: 
  render_color: True
  vis: 50  


grid:
  hash_size: 16 # 1.59M

data:
  datadir: ./data/scannet/scene0169_00
  trainskip: 1
  output: output/scannet/scene0169_00
  #exp_name: Ours_D50_3
  #exp_name: DiNNO_D50_3
  exp_name: Centralized
  load_path: output/Apartment/apartment_centralized/agent_0/checkpoint12594.pt

tracking:
  gt_pose: True


multi_agents:
  num_agents: 3
  complete_graph: True
  edges_for_dropout: [ [0,1,0.5], [0,2,0.5], [1,2,0.5] ] # [node i, node j, possibility of dropping out]
  #edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: True
  alpha: 0.15 

cam:
  H: 480
  W: 640
  fx: 574.540771
  fy: 577.583740
  cx: 322.522827
  cy: 238.558853
  png_depth_scale: 1000.
  crop_edge: 10
  near: 0
  far: 8.0