inherit_from: configs/scannet/scannet.yaml
mapping:
  bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  marching_cubes_bound: [[-0.1,8.6],[-0.1,8.9],[-0.3,3.3]]
  keyframe_every: 1
  map_every: 1


mesh: 
  render_color: True
  vis: 50  


grid:
  hash_size: 16 # 1.59M
  

data:
  datadir: ./data/scannet/scene0000_00
  trainskip: 1
  output: output/scannet/scene0000_00
  #exp_name: DiNNO_D50_1
  exp_name: Ours_D50_3
  #exp_name: DSGD_D50_3
  #exp_name: DSGT_D50_1
  load_path: output/Apartment/apartment_centralized/agent_0/checkpoint12594.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 3
  complete_graph: True
  edges_for_dropout: [ [0,1,0.5], [0,2,0.5], [1,2,0.5] ] # [node i, node j, possibility of dropping out]
  #edges_for_dropout: []
  distributed_algorithm: 'DSGT'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: False
  alpha: 0.15 # DSGD
  #alpha: 0.05 # DSGT