inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-2.4, 2.],[-0.6, 2.9],[-1.8, 3.1]]
  marching_cubes_bound: [[-2.4, 2.],[-0.6, 2.9],[-1.8, 3.1]]
  keyframe_every: 5
  map_every: 5
  
mesh:
  render_color: True
  vis: 100  

data:
  datadir: data/neural_rgbd_data/breakfast_room
  trainskip: 1
  output: output/Synthetic/br
  exp_name: br_cadmm_dropout
  load_path: output/Synthetic/br/br_centralized/agent_0/checkpoint1166.pt

tracking:
  gt_pose: True

cam:
  near: 0
  far: 5

multi_agents:
  num_agents: 3
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.8], [0,2,0.8], [1,2,0.8] ] # [node i, node j, possibility of dropping out]
  #edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: True
