inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-5.7, 3.8],[-0.2, 3.3],[-6.6, 3.6]]
  marching_cubes_bound: [[-5.7, 3.8],[-0.2, 3.3],[-6.6, 3.6]]
  keyframe_every: 5
  map_every: 5


mesh:
  render_color: True
  vis: 100  

data:
  datadir: data/neural_rgbd_data/complete_kitchen
  trainskip: 1
  output: output/Synthetic/ck
  exp_name: ck_3agents_AUQCADMM_dropout_pretrained
  load_path: output/Synthetic/ck/ck_centralized/agent_0/checkpoint1210.pt

tracking:
  gt_pose: True
  #iter: 20

cam:
  near: 0
  far: 8


multi_agents:
  num_agents: 3
  complete_graph: False
  edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.8], [0,2,0.8] ] # [node i, node j, possibility of dropping out]
  #edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: False