inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-1.5, 2.2],[-0.3, 2.2],[-2.3, 1.9]]
  marching_cubes_bound: [[-1.5, 2.2],[-0.3, 2.2],[-2.3, 1.9]]
  keyframe_every: 5
  map_every: 5


mesh:
  render_color: True
  vis: 100  


data:
  datadir: data/neural_rgbd_data/morning_apartment
  trainskip: 1
  output: output/Synthetic/ma
  #exp_name: ma_10agents_AUQCADMM
  #exp_name: ma_3agents_AUQCADMM_dropout_pretrained
  exp_name: ma_3agents_dropout_pretrained
  load_path: output/Synthetic/ma/ma_centralized/agent_0/checkpoint919.pt


tracking:
  gt_pose: True
  #iter: 20


multi_agents:
  num_agents: 3
  complete_graph: False
  edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.8], [0,2,0.8] ] # [node i, node j, possibility of dropping out]
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: False