inherit_from: configs/Azure/azure.yaml
mapping:
  bound: [ [-6.5,8.], [-1.5,3.5], [-4.5,3.6] ]
  marching_cubes_bound: [ [-6.5,8.], [-1.5,3.5], [-4.5,3.6] ]

mesh:
  render_color: True
  
data:
  datadir: ./data/Apartment
  trainskip: 1
  output: output/Apartment
  exp_name: three_agents

tracking:
  gt_pose: True

multi_agents:
  num_agents: 3 
  edges_list: [[0,1], [0,2], [1,2]]
  distributed_algorithm: 'CADMM'
  rho: 0.0001
  com_every: 5
  track_uncertainty: False
