inherit_from: configs/Azure/azure.yaml
mapping:
  bound: [[-1.5,3.5],[-4.5,3.6],[-6.5,8.]]
  marching_cubes_bound: [[-1.5,3.5],[-4.5,3.6],[-6.5,8.]]

mesh:
  render_color: True
  
data:
  datadir: C:\Users\hongr\Documents\uiuc\Thesis\codes\git\multi_agent_SLAM\multi_agent_SLAM\Datasets\Apartment
  trainskip: 1
  output: output/Apartment
  exp_name: demo