inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3,3],[-4,2.5],[-2,2.5]]
  marching_cubes_bound: [[-2.2,2.6],[-3.4,2.1],[-1.4,2.0]]
  keyframe_every: 5
  map_every: 5


mesh: 
  render_color: True
  vis: 50  


data:
  datadir: data/Replica/office0
  trainskip: 1
  output: output/Replica/office0
  exp_name: Pretrain_AUQCADMM_D80_S1000_3
  #exp_name: Pretrain_CADMM_D80_3
  #exp_name: CADMM_D80_3
  load_path: output/Apartment/apartment_centralized/agent_0/checkpoint12594.pt

tracking:
  gt_pose: True


multi_agents:
  num_agents: 3 
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.8], [0,2,0.8], [1,2,0.8] ] # [node i, node j, possibility of dropping out]
  #edges_for_dropout: []
  distributed_algorithm: 'CADMM'
  rho: 0.0001
  track_uncertainty: True
  fix_decoder: False

