inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3,3],[-4,2.5],[-2,2.5]]
  marching_cubes_bound: [[-2.2,2.6],[-3.4,2.1],[-1.4,2.0]]
  keyframe_every: 5
  map_every: 5


mesh: 
  render_color: True
  vis: 100  


data:
  datadir: data/Replica/office0
  trainskip: 1
  output: output/Replica/office0
  #exp_name: 3agents_cadmm_dropout
  exp_name: 3agents_AUQCADMM_dropout
  load_path: output/Replica/office0/centralized/agent_0/checkpoint1999.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 3 
  complete_graph: False
  edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.8], [0,2,0.8], [1,2,0.8] ] # [node i, node j, possibility of dropping out]
  # edges_list: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: True
