inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-2,3.2],[-1.7,2.7],[-1.2,2.0]]
  marching_cubes_bound: [[-1.9,3.1],[-1.6,2.6],[-1.1,1.8]]
  keyframe_every: 5
  map_every: 5
  

mesh: 
  render_color: True
  vis: 100  


data:
  datadir: data/Replica/office1
  trainskip: 1
  output: output/Replica/office1
  exp_name: 3agents_AUQCADMM_dropout
  load_path: output/Replica/office1/centralized/agent_0/checkpoint1999.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 3
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.8], [0,2,0.8], [1,2,0.8] ] # [node i, node j, possibility of dropping out]
  #edges_for_dropout: []
  distributed_algorithm: 'CADMM'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: True
