inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3.6,3.2],[-3.0,5.5],[-1.4,1.7]]
  marching_cubes_bound: [[-3.5,3.1],[-2.9,5.4],[-1.3,1.6]]
  keyframe_every: 5
  map_every: 5


mesh: 
  render_color: True
  vis: 50  


data:
  datadir: data/Replica/office2
  trainskip: 1
  output: output/Replica/office2
  exp_name: Pretrain_AUQCADMM_D80_S100_2
  #exp_name: Pretrain_CADMM_D80_2
  #exp_name: Pretrain_CADMM_D0
  #exp_name: 3agents_cadmm_dropout_2
  #load_path: output/Replica/office2/centralized/agent_0/checkpoint1999.pt
  load_path: output/Apartment/apartment_centralized/agent_0/checkpoint12594.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 3
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  #edges_for_dropout: [ [0,1,0.8], [0,2,0.8], [1,2,0.8] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'CADMM'
  rho: 0.0001
  track_uncertainty: True
  fix_decoder: True

