inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.4,5.5],[-2.5,4.4],[-1.4,1.8]]
  marching_cubes_bound: [[-1.3,5.4],[-2.4,4.3],[-1.3,1.7]]
  keyframe_every: 5
  map_every: 5

mesh:
  render_color: True
  vis: 100  

data:
  datadir: data/Replica/office4
  trainskip: 1
  output: output/Replica/office4
  exp_name: office4_20agents_AUQCADMM
  #exp_name: office4_20agents

tracking:
  gt_pose: True
  #iter: 20

multi_agents:
  num_agents: 20
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  #edges_for_dropout: [ [0,1,0.6], [0,2,0.6] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'CADMM'
  rho: 0.0001
  track_uncertainty: False