inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3,3],[-4,2.5],[-2,2.5]]
  marching_cubes_bound: [[-2.2,2.6],[-3.4,2.1],[-1.4,2.0]]
  keyframe_every: 5
  map_every: 5


mesh: 
  render_color: True
  vis: 50  


data:
  datadir: data/Replica/office0
  trainskip: 1
  output: output/Replica/office0
  #exp_name: DiNNO_D40_3
  #exp_name: MACIM_D40_3
  exp_name: Ours_D30_1
  load_path: output/Apartment/apartment_centralized/agent_0/checkpoint12594.pt

tracking:
  gt_pose: True


multi_agents:
  num_agents: 3 
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.3], [0,2,0.3], [1,2,0.3] ] # [node i, node j, possibility of dropping out]
  #edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: True
  alpha: 0.15

