inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.0,6.1],[-3.4,1.9],[-3.1,0.8]]
  marching_cubes_bound: [[-0.9,6.0],[-3.3,1.8],[-3.0,0.7]]
  keyframe_every: 5
  map_every: 5
  #iter: 20


mesh:
  render_color: True
  vis: 100  


data:
  datadir: data/Replica/room2
  trainskip: 1
  output: output/Replica/room2
  #exp_name: room2_10agents_AUQCADMM
  exp_name: room2_3agents_AUQCADMM_pretrained
  load_path: output/Replica/office0/centralized/agent_0/checkpoint1999.pt
  

tracking:
  gt_pose: True
  #iter: 20


multi_agents:
  num_agents: 3
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  #edges_for_dropout: [ [0,1,0.6], [0,2,0.6] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: True
