inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]
  marching_cubes_bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]
  keyframe_every: 1
  map_every: 1


mesh: 
  render_color: True
  vis: 60  


data:
  datadir: data/Replica/room1
  trainskip: 1
  output: output/Replica/room1
  #exp_name: Ours_D50_3
  #exp_name: DiNNO_D50_3
  #exp_name: DSGD_D50_3
  exp_name: DSGT_D50_3
  load_path: output/Apartment/apartment_centralized/agent_0/checkpoint12594.pt


tracking:
  gt_pose: True


multi_agents:
  num_agents: 3
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.5], [0,2,0.5], [1,2,0.5] ] # [node i, node j, possibility of dropping out]
  edges_for_dropout: []
  distributed_algorithm: 'DSGT'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: False
  #alpha: 0.15 # DSGD
  alpha: 0.10 # DSGT