inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.0,6.1],[-3.4,1.9],[-3.1,0.8]]
  marching_cubes_bound: [[-0.9,6.0],[-3.3,1.8],[-3.0,0.7]]
  #iter: 20


mesh:
  render_color: True
  vis: 100  


data:
  datadir: data/Replica/room2
  trainskip: 1
  output: output/Replica/room2
  exp_name: room2_3agents 
  #exp_name: room2_centralized 


tracking:
  gt_pose: True
  #iter: 20


multi_agents:
  num_agents: 3 
  edges_list: [[0,1], [0,2], [1,2]]
  # num_agents: 1
  # edges_list: []
  distributed_algorithm: 'CADMM'
  rho: 0.001
  com_every: 5
  track_uncertainty: True
