inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]
  marching_cubes_bound: [[-5.6,1.4],[-3.2,2.8],[-1.6,1.8]]
  keyframe_every: 5
  map_every: 5


mesh: 
  render_color: True
  vis: 100  


data:
  datadir: data/Replica/room1
  trainskip: 1
  output: output/Replica/room1
  exp_name: 3agents_cadmm_dropout
  load_path: output/Replica/room1/centralized/agent_0/checkpoint1999.pt

tracking:
  gt_pose: True


multi_agents:
  num_agents: 3
  complete_graph: True
  #edges_list: [[0,1], [0,2], [1,2]]
  edges_for_dropout: [ [0,1,0.8], [0,2,0.8], [1,2,0.8] ] # [node i, node j, possibility of dropping out]
  #edges_for_dropout: []
  distributed_algorithm: 'AUQ_CADMM'
  rho: 0.0001
  track_uncertainty: False
  fix_decoder: True